export default {
    SAVE_OUTCOME: 'SAVE_OUTCOME',
    GET_OUTCOMES_BY_MONTH: 'GET_OUTCOMES_BY_MONTH',
    GET_OUTCOMES_BY_RANGE: 'GET_OUTCOMES_BY_RANGE',
    DELETE_OUTCOME: 'DELETE_OUTCOME',
    UPDATE_OUTCOME: 'UPDATE_OUTCOME'
}